# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 01:03
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('sites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('frequency', models.CharField(max_length=255)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchSocialMediaJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=255)),
                ('last_run', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(max_length=254)),
                ('searchjobs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.SearchSocialMedia')),
            ],
        ),
        migrations.CreateModel(
            name='SearchSocialMediaJobResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_run', models.DateTimeField(auto_now=True)),
                ('searchsocialmediajob_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.SearchSocialMediaJob')),
            ],
        ),
    ]
