# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Searches',
            new_name='Search',
        ),
        migrations.RenameModel(
            old_name='SearchJobs',
            new_name='SearchJob',
        ),
    ]
