# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20170820_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='searchjobs_id',
        ),
        migrations.RemoveField(
            model_name='searchjob',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.DeleteModel(
            name='SearchJob',
        ),
    ]
